members-only/config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  post 'posts/create'
  get 'posts/index'
  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "static_pages#lol"
end

members-only/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

members-only/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy
  before_create :remember

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def remember
      self.remember_digest = User.digest(User.new_token)
    end
end

members-only/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  attr_writer :current_user
  helper_method :logged_in?

  def login(user)
    new_token = User.new_token
    cookies.permanent[:remember_token] = new_token
    user.update_attribute(:remember_digest, User.digest(new_token))
    @current_user = user
  end

  def logout
    user = current_user
    cookies.delete :remember_token
    user.update_attribute(:remember_digest, nil)
    @current_user = nil
  end

  def current_user
    remember_digest = User.digest(cookies.permanent[:remember_token])
    @current_user ||= User.find_by(remember_digest: remember_digest)
  end

  # Before filter
  def logged_in
    return if logged_in?

    flash[:warning] = "Woah, woah! What's the password?"
    redirect_to login_path
  end

  private

    def logged_in?
      !current_user.nil?
    end
end

members-only/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in, only: %i[new create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    flash[:success] = "Heh. That's a good one."
    redirect_to posts_index_path
  end

  def index
    @posts = Post.all
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

members-only/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      login @user
      flash[:success] = "Alright, come in. Quickly!"
      redirect_to posts_index_path
    else
      flash.now[:danger] = "You're not on the list. Get lost!"
      render :new
    end
  end

  def destroy
    logout
    flash[:success] = "Remember, first rule about the clubhouse . . ."
    redirect_to root_path
  end
end

members-only/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def lol
  end
end

members-only/app/helpers/posts_helper.rb
module PostsHelper
end

members-only/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

members-only/app/views/posts/index.html.erb
<% provide(:title, "Posts") %>
<h1>Posts</h1>
<%= "<p><em>Bet you wish you knew who wrote these...</em></p>".html_safe unless logged_in? %>
<% @posts.includes(:user).each do |post| %>
  <h5><%= post.title %></h5>
  <% if logged_in? %>
    <strong>Author:</strong>
    <%= post.user.name %>
  <% end %>
  <p><%= post.body %></p>
<% end %>

members-only/app/views/posts/new.html.erb
<% provide(:title, "New Post") %>
<h1>New post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with scope: :post, url: posts_create_path, local: true do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control" %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>