invitr/config/routes.rb
Rails.application.routes.draw do
  get 'invitations/new'
  get 'invitations/create'
  post 'invitations/accept/:id', to: 'invitations#accept', as: 'invitations/accept/'
  post 'invitations/decline/:id', to: 'invitations#decline', as: 'invitations/decline/'
  get 'events/new'
  get 'events/create'
  get 'events/show'
  root 'static#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/profile', to: 'users#show'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :events
  resources :invitations
end

invitr/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :host, class_name: "User"
  has_many :invitations, dependent: :destroy
  has_many :attendees, through: :invitations
  default_scope { order(:date) }
  scope :upcoming, -> { where("events.date > ?", Time.zone.now) }
  scope :past,     -> { where("events.date <= ?", Time.zone.now).reverse_order }
  validates :title, presence: true
  validates :date, presence: true

  def invitation_pending?(user)
    invitations.find_by(attendee_id: user.id).status == "pending" && 
      not_host?(user)
  end

  def invitation_declined?(user)
    invitations.find_by(attendee_id: user.id).status == "declined" &&
      not_host?(user)
  end

  def invitation_accepted?(user)
    invitations.find_by(attendee_id: user.id).status == "accepted" && 
      not_host?(user)
  end

  def not_invited?(user)
    !attendees.include?(user) && not_host?(user)
  end

  def host?(user)
    user == host
  end

  def not_host?(user)
    user != host
  end

  def past?
    Event.past.include?(self)
  end
end

invitr/app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: "User"

  enum status: { pending: 0,
                 accepted: 1,
                 declined: 2 }

  def accept!
    return false if accepted?

    update(status: "accepted")
  end

  def decline!
    return false if declined?

    update(status: "declined")
  end

  def accepted?
    status == "accepted"
  end

  def pending?
    status == "pending"
  end

  def declined?
    status == "declined"
  end
end

invitr/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :remember_token
  validates :name, presence: true, uniqueness: { case_sensitive: false },
                   format: { without: /\s/ }
  validates :password, presence: true
  has_many :hosted_events, class_name: "Event", foreign_key: "host_id",
                           dependent: :destroy
  has_many :invitations, foreign_key: "attendee_id", dependent: :destroy

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def remember
      self.remember_digest = User.digest(User.new_token)
    end
end

invitr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  attr_writer :current_user
  helper_method :logged_in?, :current_user

  def login(user)
    new_token = User.new_token
    cookies.permanent[:remember_token] = new_token
    user.update_attribute(:remember_digest, User.digest(new_token))
    @current_user = user
  end

  def logout
    user = current_user
    cookies.delete :remember_token
    user.update_attribute(:remember_digest, nil)
    @current_user = nil
  end

  def current_user
    remember_digest = User.digest(cookies.permanent[:remember_token])
    @current_user ||= User.find_by(remember_digest: remember_digest)
  end

  def logged_in
    return if logged_in?

    flash[:warning] = "Please log in or create an account"
    redirect_to login_path
  end

  private

    def logged_in?
      !current_user.nil?
    end
end

invitr/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def new
    @event = Event.new
  end

  def create
    @current_user = current_user
    @event = @current_user.hosted_events.build(event_params)
    if @event.save
      flash[:success] = "Event created"
      redirect_to @event
    else
      flash.now[:danger] = @event.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @current_user = current_user

    @invitation = if @event.host?(@current_user)
                    Invitation.new
                  else
                    Invitation.find_or_initialize_by(event: @event,
                                                     attendee: @current_user)
                  end
  end

  private

    def event_params
      params.require(:event).permit(:title, :date)
    end
end

invitr/app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @event = Event.find_by(id: params[:format])
    @users = User.where.not(id: @event.attendees.ids).where.not(id: @event.host.id)
    @invitation = Invitation.new(event: @event)
  end

  def create
    @invitation = Invitation.new(invitation_params)
    if @invitation.save
      flash[:success] = "Invitation sent!"
      @event = @invitation.event
      redirect_to @event
    else
      flash.now[:danger] = @invitation.errors.full_messages.to_sentence
    end
  end

  def accept
    invitation = Invitation.find(params[:id])

    if invitation.accept!
      flash[:success] = "You have accepted the invitation!"
    else
      flash[:danger] = "You cannot accept this invitation"
    end
    redirect_to(invitation.event)
  end

  def decline
    invitation = Invitation.find(params[:id])

    if invitation.decline!
      flash[:success] = "You have declined the invitation."
    else
      flash[:danger] = "You cannot decline this invitation."
    end
    redirect_to(invitation.event)
  end

  private

    def invitation_params
      params.require(:invitation).permit(:attendee_id, :event_id, :status)
    end
end

invitr/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      login @user
      flash[:success] = "Logged in successfully"
      redirect_to @user
    else
      flash.now[:danger] = "Invalid username or password"
      render :new
    end
  end

  def destroy
    logout
    flash[:success]
    redirect_to root_path
  end
end

invitr/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

invitr/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account created"
      login(@user)
      redirect_to @user
    else
      flash.now[:danger] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @user = params[:id].nil? ? current_user : User.find(params[:id])
    @upcoming_events = @user.hosted_events.upcoming
    @past_events = @user.hosted_events.past.first(3)
    @invitations = @user.invitations
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

invitr/app/helpers/events_helper.rb
module EventsHelper
end

invitr/app/helpers/invitations_helper.rb
module InvitationsHelper
end

invitr/app/helpers/sessions_helper.rb
module SessionsHelper
end

invitr/app/helpers/users_helper.rb
module UsersHelper
end

invitr/app/views/events/_event.html.erb
<div class="card">
  <div class="card-header">
    <span class="mb-0">
      <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse-<%= event.id %>">
        <%= event.title %>
      </button>
      <% if event.past? %>
        <%= distance_of_time_in_words(Time.now, event.date) %> ago
      <% else %>
        in <%= distance_of_time_in_words(Time.now, event.date) %>
      <% end %>
    </span>
  </div>
  <div id="collapse-<%= event.id %>" class="collapse" data-parent="#accordion">
    <div class="card-body">
      Host: <%= link_to event.host.name, event.host %></br>
      When: <%= event.date %></br>
      Details: <%= link_to "Show", event %>
    </div>
  </div>
</div>

invitr/app/views/events/_interactions.html.erb
    <% if @event.past? %>
      <span class="badge badge-secondary">This event is over</span>
    <% elsif @event.host?(@current_user) %>
      <%= button_to "Invite somebody!", invitations_new_path(@event.id), method: :get, class: "btn btn-outline-primary" %>
    <% elsif @event.not_invited?(@current_user) %>
      <%= form_with model: @invitation, url: invitations_path, method: :post, local: true do |f| %>
        <%= f.hidden_field :attendee_id, value: @current_user.id %>
        <%= f.hidden_field :event_id, value: @event.id %>
        <%= f.hidden_field :status, value: "accepted" %>
        <%= f.submit "Attend this event!", class: "btn btn-outline-success" %>
      <% end %>
    <% elsif @event.invitation_pending?(@current_user) %>
      <span class="badge badge-info">You've been invited!</span><br>
      <div class="btn-group">
        <%= button_to "I'm going!", invitations_accept_path(@invitation), class: "btn btn-outline-success" %>
        <%= button_to "I'm not going", invitations_decline_path(@invitation), class: "btn btn-outline-danger" %>
      </div>
    <% elsif @event.invitation_declined?(@current_user) %>
      <span class="badge badge-danger">You've declined</span><br>
      <%= button_to "I changed my mind!", invitations_accept_path(@invitation), class: "btn btn-outline-success" %>
    <% elsif @event.invitation_accepted?(@current_user) %>
      <span class="badge badge-success">You're going!</span>
      <%= button_to "I changed my mind...", invitations_decline_path(@invitation), class: "btn btn-outline-danger" %>
    <% end %>

invitr/app/views/events/_none.html.erb
<div class="card">
  <div class="card-header">
    <button class="btn btn-link" disabled>
      There aren't any!
    </button>
  </div>
</div>

invitr/app/views/events/index.html.erb
<% provide(:title, "Events") %>
<h1>Events</h1>
<%= button_to "Create new event", new_event_path, method: :get, class: "btn btn-outline-primary" %>
<br>
<div class="row">
  <aside class="col-md-6">
    <h3>Upcoming events</h3>
    <% if @upcoming_events.empty? %>
      <%= render "events/none" %>
    <% else %>
      <div id="accordion">
        <%= render @upcoming_events %>
      </div>
    <% end %>
  </aside>
  <div class="col-md-6">
    <h3>Past events</h3>
    <% if @past_events.empty? %>
      <%= render "events/none" %>
    <% else %>
      <div id="accordion">
        <%= render @past_events %>
      </div>
    <% end %>
  </div>
</div><br>

invitr/app/views/events/new.html.erb
<% provide(:title, "New Event") %>
<h1>New Event</h1>
<div class = "row">
  <div class = "col">
    <%= form_with model: @event, local: true do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :date %>
      <%= f.datetime_local_field :date, class: "form-control" %>

      <%= f.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

invitr/app/views/events/show.html.erb
<% provide(:title, "Event details") %>
<h1><%= @event.title %></h1>
<div class="row">
  <aside class="col-md-3">
    <strong>Host:</strong> <%= link_to @event.host.name, @event.host %><br>
    <strong>When:</strong> <%= @event.date %><br><br>
    <strong>Attendees:</strong>
  </aside>
  <div class="col-md-9">
    <%= render "interactions" %>
  </div>
</div>
<div class="row">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <% @event.invitations.each do |invitation| %>
        <tr>
          <td scope="col">
            <%= link_to invitation.attendee.name, invitation.attendee %>
          </td>
          <td scope="col">
            <%= render partial: "shared/invitation_status", locals: { invitation: invitation } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

invitr/app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "Invitr", root_path, class: "navbar-brand" %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Home <span class="sr-only"></span>'.html_safe, root_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to " My Profile", profile_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to " Events", events_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to " Users", users_path, class: "nav-link" %></li>
        <% end%>
      </ul>
      <ul class="nav navbar-nav ml-auto">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to '<i class="fas fa-sign-out-alt"></i> Sign Out'.html_safe, logout_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to '<i class="fas fa-user"></i> Sign Up'.html_safe, signup_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '<i class="fas fa-sign-in-alt"></i> Login'.html_safe, login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul> 
    </nav>

invitr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

invitr/app/views/shared/_invitation_status.html.erb
<% case invitation.status %>
<% when "pending" %>
  <span class="badge badge-secondary"><%= invitation.status %></span>
<% when "accepted" %>
  <span class="badge badge-success"><%= invitation.status %></span>
<% when "declined" %>
  <span class="badge badge-danger"><%= invitation.status %></span>
<% end %>

invitr/app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
</li>

invitr/app/views/users/index.html.erb
<% provide(:title, "All users") %>
<h1>All users</h1>

<%= will_paginate %>
<ul>
  <%= render @users %>
</ul>
<%= will_paginate %>

invitr/app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col">
    <%= form_with model: @user, local: true do |f| %>
      <%= f.label :name, "Username" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

invitr/app/views/users/show.html.erb
<% provide(:title, "Profile") %>
<h1><%= @user.name %></h1>
<div class="row">
  <aside class="col-md-6">
    <h3>Hosted events</h3>
    <% if @upcoming_events.empty? %>
      <%= render "events/none" %>
    <% else %>
      <div id="accordion">
        <%= render @upcoming_events %>
      </div>
    <% end %>
  </aside>
  <div class="col-md-6">
    <h3>Past events</h3>
    <% if @past_events.empty? %>
      <%= render "events/none" %>
    <% else %>
      <div id="accordion">
        <%= render @past_events %>
      </div>
    <% end %>
  </div>
</div><br>
<h3>Invitations</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Event</th>
      <th scope="col">When?</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @user.invitations.each do |invitation| %>
      <% unless invitation.event.past? %>
        <tr>
          <td scope="col">
            <%= link_to invitation.event.title, invitation.event %>
          </td>
          <td scope="col">
            in <%= distance_of_time_in_words(Time.now, invitation.event.date) %>
          </td>
          <td scope="col">
            <%= render partial: "shared/invitation_status", locals: { invitation: invitation } %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>